### PR TITLE
Fixed installation error when the settings file can't be written

### LINKED ISSUE #30: Add write perms to settings.php before release, remove after

### PR DESCRIPTION
**Pull request by matthijs-va**
fixes #30

### CODE REVIEW

File: src/RoboFileBase.php [hunk 1]
```diff
@@ -420,13 +422,18 @@ public function digipolisInstallDrupal8(
...
 
-        if (is_file($app_root . '/sites/default/settings.php')) {
-            include $app_root . '/sites/default/settings.php';
+        if (is_file($site_path . '/settings.php')) {
+            chmod($site_path . '/settings.php', 664);
+            include $site_path . '/settings.php';
         }
-        elseif (is_file($app_root . '/sites/default/settings.local.php')) {
-            include $app_root . '/sites/default/settings.local.php';
+        elseif (is_file($site_path . '/settings.local.php')) {
```
Comment (daften) [inline src/RoboFileBase.php]: When is there a situation where there is no settings.php but there is a settings.local.php?

**Comment by matthijs-va** [comment]
fixes #30

File: src/RoboFileBase.php (hunk 1 above)
Comment (matthijs-va) [reply src/RoboFileBase.php]: Don't know, but it's supported ;-)
