### PR TITLE
Fixes #5: Replace certain drupal console commands with drush commands…

### LINKED ISSUE #5: Switch to drush for deployment flow?
Problem:
When faulty config is imported, every drupal console command fails, because the bootstrap that happens on each command fails. That means the restore at the end of the failed deploy fails as well.

- First put an issue in drupal-console project if this can be fixed at a higher level.
- Replace certain drupal console commands with drush commands to make sure the flow keeps working. E.g. the database restore.

### PR DESCRIPTION
**Pull request by Jelle-S**
… to make sure the flow keeps working.

### CODE REVIEW

File: src/RoboFileBase.php [hunk 1]
```diff
@@ -216,20 +216,29 @@ public function digipolisUpdateDrupal8($opts = ['config-import' => false])
...
-              ->updateDb();
+            ->drupalRootDirectory($this->getConfig()->get('digipolis.root.web'))
+            ->maintenance();
+
+        // When uninstalling modules inside update hook,
+        // we get "dependency on a non-existent service" exception.
+        // Therefore switch to drush for excecuting update hooks.
+        $collection
+            ->taskExecStack()
+            ->exec('cd ' . $this->getConfig()->get('digipolis.root.web') . ' && ../vendor/bin/drush updb --yes');
```
Comment (daften) [inline src/RoboFileBase.php]: Why not use the --root option for drush instead of cd ...
Or use the drush command stack (https://github.com/boedah/robo-drush)?

File: src/RoboFileBase.php [hunk 2]
```diff
@@ -216,20 +216,29 @@ public function digipolisUpdateDrupal8($opts = ['config-import' => false])
...
-                // Todo: find a way to do this with drupal console.
-                ->exec('cd ' . $this->getConfig()->get('digipolis.root.web') . ' && ../vendor/bin/drush locale-check')
-                ->exec('cd ' . $this->getConfig()->get('digipolis.root.web') . ' && ../vendor/bin/drush locale-update')
+            ->exec('cd ' . $this->getConfig()->get('digipolis.root.web') . ' && ../vendor/bin/drush locale-check')
+            ->exec('cd ' . $this->getConfig()->get('digipolis.root.web') . ' && ../vendor/bin/drush locale-update')
             ->taskDrupalConsoleStack('vendor/bin/drupal')
-              ->drupalRootDirectory($this->getConfig()->get('digipolis.root.web'))
-              ->maintenance(false);
+            ->drupalRootDirectory($this->getConfig()->get('digipolis.root.web'))
+            ->cacheRebuild()
```
Comment (daften) [inline src/RoboFileBase.php]: Doesn't maintenance off mean cache rebuild automatically?

File: src/RoboFileBase.php (hunk 1 above)
Comment (Jelle-S) [inline src/RoboFileBase.php]: Will do in a follow-up
